name: Pull Request

on:
  pull_request:
    types: [opened, ready_for_review]
    branches-ignore:
      - "main"
      - "release-**"

jobs:
  pull_request:
    if: ${{ !github.event.pull_request.draft }}
    name: Create PR alarm
    runs-on: ubuntu-latest
    steps:
      - name: Send comment alarm message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            새로운 PR이 생성되었습니다! 🎫

            📰 PR 제목: ${{ github.event.pull_request.title }}
            👤 PR 작성자: ${{ github.event.pull_request.user.login }}
            🫂 리뷰어: ${{ github.event.pull_request.requested_reviewers[0].login }}

            다음 [링크](${{ github.event.pull_request.html_url }})를 확인해주세요!
